### ISSUE TITLE
npm install broken

### ISSUE THREAD

**Issue by vovavoevidka** [eleks-front-end/eslint-config-eleks#1]
```
$ npm install @eleks/eslint-config-eleks --save-dev
```

not work's for me

**Comment by vovavoevidka** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '@eleks/eslint-config-eleks',
1 verbose cli   '--save-dev' ]
2 info using npm@1.4.3
3 info using node@v0.10.26
4 verbose node symlink C:\Program Files\nodejs\node.exe
5 verbose cache add [ '@eleks/eslint-config-eleks', null ]
6 verbose cache add name=undefined spec="@eleks/eslint-config-eleks" args=["@eleks/eslint-config-eleks",null]
7 verbose parsed url { protocol: null,
7 verbose parsed url   slashes: null,
7 verbose parsed url   auth: null,
7 verbose parsed url   host: null,
7 verbose parsed url   port: null,
7 verbose parsed url   hostname: null,
7 verbose parsed url   hash: null,
7 verbose parsed url   search: null,
7 verbose parsed url   query: null,
7 verbose parsed url   pathname: '@eleks/eslint-config-eleks',
7 verbose parsed url   path: '@eleks/eslint-config-eleks',
7 verbose parsed url   href: '@eleks/eslint-config-eleks' }
8 verbose cache add name="" spec="eleks/eslint-config-eleks" args=["","eleks/eslint-config-eleks"]
9 verbose parsed url { protocol: null,
9 verbose parsed url   slashes: null,
9 verbose parsed url   auth: null,
9 verbose parsed url   host: null,
9 verbose parsed url   port: null,
9 verbose parsed url   hostname: null,
9 verbose parsed url   hash: null,
9 verbose parsed url   search: null,
9 verbose parsed url   query: null,
9 verbose parsed url   pathname: 'eleks/eslint-config-eleks',
9 verbose parsed url   path: 'eleks/eslint-config-eleks',
9 verbose parsed url   href: 'eleks/eslint-config-eleks' }
10 silly lockFile 8ed236b7-eleks-eslint-config-eleks eleks/eslint-config-eleks
11 verbose lock eleks/eslint-config-eleks C:\Users***_\AppData\Roaming\npm-cache\8ed236b7-eleks-eslint-config-eleks.lock
12 info maybeGithub Attempting eleks/eslint-config-eleks from git://github.com/eleks/eslint-config-eleks
13 silly lockFile 2ca59e6a-ub-com-eleks-eslint-config-eleks git://github.com/eleks/eslint-config-eleks
14 verbose lock git://github.com/eleks/eslint-config-eleks C:\Users\**__\AppData\Roaming\npm-cache\2ca59e6a-ub-com-eleks-eslint-config-eleks.lock
15 verbose addRemoteGit [ 'git://github.com/eleks/eslint-config-eleks', 'master' ]
16 verbose git remote.origin.url git://github.com/eleks/eslint-config-eleks
17 error git fetch -a origin (git://github.com/eleks/eslint-config-eleks) remote: Repository not found.
17 error git fetch -a origin (git://github.com/eleks/eslint-config-eleks) fatal: repository 'https://github.com/eleks/eslint-config-eleks/' not found
18 silly lockFile 2ca59e6a-ub-com-eleks-eslint-config-eleks git://github.com/eleks/eslint-config-eleks
19 silly lockFile 2ca59e6a-ub-com-eleks-eslint-config-eleks git://github.com/eleks/eslint-config-eleks
20 info maybeGithub Attempting eleks/eslint-config-eleks from git+ssh://git@github.com:eleks/eslint-config-eleks
21 silly lockFile d84d2d9c-ub-com-eleks-eslint-config-eleks git@github.com:eleks/eslint-config-eleks
22 verbose lock git@github.com:eleks/eslint-config-eleks C:\Users\_**_\AppData\Roaming\npm-cache\d84d2d9c-ub-com-eleks-eslint-config-eleks.lock
23 verbose addRemoteGit [ 'git@github.com:eleks/eslint-config-eleks', 'master' ]
24 warn `git config --get remote.origin.url` returned wrong result (git@github.com:eleks/eslint-config-eleks)
25 error git clone git@github.com:eleks/eslint-config-eleks Cloning into bare repository 'C:\Users\**__\AppData\Roaming\npm-cache_git-remotes\git-github-com-eleks-eslint-config-eleks-d84d2d9c'...
25 error git clone git@github.com:eleks/eslint-config-eleks fatal: Could not read from remote repository.
25 error git clone git@github.com:eleks/eslint-config-eleks
25 error git clone git@github.com:eleks/eslint-config-eleks Please make sure you have the correct access rights
25 error git clone git@github.com:eleks/eslint-config-eleks and the repository exists.
26 silly lockFile d84d2d9c-ub-com-eleks-eslint-config-eleks git@github.com:eleks/eslint-config-eleks
27 silly lockFile d84d2d9c-ub-com-eleks-eslint-config-eleks git@github.com:eleks/eslint-config-eleks
28 silly lockFile 8ed236b7-eleks-eslint-config-eleks eleks/eslint-config-eleks
29 silly lockFile 8ed236b7-eleks-eslint-config-eleks eleks/eslint-config-eleks
30 error addLocal Could not install eleks/eslint-config-eleks
31 error Error: ENOENT, stat 'd:\development\_**_\eleks\eslint-config-eleks'
32 error If you need help, you may report this *entire_ log,
32 error including the npm and node versions, at:
32 error     http://github.com/npm/npm/issues
33 error System Windows_NT 6.2.9200
34 error command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "@eleks/eslint-config-eleks" "--save-dev"
35 error cwd d:\****
36 error node -v v0.10.26
37 error npm -v 1.4.3
38 error path d:****\eleks\eslint-config-eleks
39 error code ENOENT
40 error errno 34
41 verbose exit [ 34, true ]

**Comment by husa** [comment]
@vovavoevidka make sure you're using latest node and npm versions, then try `npm cache clear`, after all, if you're using UNIX machine try to use `sudo`

**Comment by vovavoevidka** [comment]
I had old version of npm, fixed.
Thks.

**Comment by husa** [comment]
@vovavoevidka np
